// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CurrentConditions struct {
	Datetime       *string   `json:"datetime,omitempty"`
	DatetimeEpoch  *int32    `json:"datetimeEpoch,omitempty"`
	Temp           *float64  `json:"temp,omitempty"`
	Feelslike      *float64  `json:"feelslike,omitempty"`
	Humidity       *float64  `json:"humidity,omitempty"`
	Dew            *float64  `json:"dew,omitempty"`
	Precip         *float64  `json:"precip,omitempty"`
	Precipprob     *float64  `json:"precipprob,omitempty"`
	Snow           *float64  `json:"snow,omitempty"`
	Snowdepth      *float64  `json:"snowdepth,omitempty"`
	Preciptype     []*string `json:"preciptype,omitempty"`
	Windgust       *float64  `json:"windgust,omitempty"`
	Windspeed      *float64  `json:"windspeed,omitempty"`
	Winddir        *float64  `json:"winddir,omitempty"`
	Pressure       *float64  `json:"pressure,omitempty"`
	Visibility     *float64  `json:"visibility,omitempty"`
	Cloudcover     *float64  `json:"cloudcover,omitempty"`
	Solarradiation *float64  `json:"solarradiation,omitempty"`
	Solarenergy    *float64  `json:"solarenergy,omitempty"`
	Uvindex        *int32    `json:"uvindex,omitempty"`
	Conditions     *string   `json:"conditions,omitempty"`
	Icon           *string   `json:"icon,omitempty"`
	Stations       []*string `json:"stations,omitempty"`
	Source         *string   `json:"source,omitempty"`
	Sunrise        *string   `json:"sunrise,omitempty"`
	SunriseEpoch   *int32    `json:"sunriseEpoch,omitempty"`
	Sunset         *string   `json:"sunset,omitempty"`
	SunsetEpoch    *int32    `json:"sunsetEpoch,omitempty"`
	Moonphase      *float64  `json:"moonphase,omitempty"`
}

type Day struct {
	Datetime         *string   `json:"datetime,omitempty"`
	DatetimeEpoch    *int32    `json:"datetimeEpoch,omitempty"`
	Tempmax          *float64  `json:"tempmax,omitempty"`
	Tempmin          *float64  `json:"tempmin,omitempty"`
	Temp             *float64  `json:"temp,omitempty"`
	Feelslikemax     *float64  `json:"feelslikemax,omitempty"`
	Feelslikemin     *float64  `json:"feelslikemin,omitempty"`
	Feelslike        *float64  `json:"feelslike,omitempty"`
	Dew              *float64  `json:"dew,omitempty"`
	Humidity         *float64  `json:"humidity,omitempty"`
	Precip           *float64  `json:"precip,omitempty"`
	Precipprob       *float64  `json:"precipprob,omitempty"`
	Precipcover      *float64  `json:"precipcover,omitempty"`
	Preciptype       []*string `json:"preciptype,omitempty"`
	Snow             *float64  `json:"snow,omitempty"`
	Snowdepth        *float64  `json:"snowdepth,omitempty"`
	Windgust         *float64  `json:"windgust,omitempty"`
	Windspeed        *float64  `json:"windspeed,omitempty"`
	Winddir          *float64  `json:"winddir,omitempty"`
	Pressure         *float64  `json:"pressure,omitempty"`
	Cloudcover       *float64  `json:"cloudcover,omitempty"`
	Visibility       *float64  `json:"visibility,omitempty"`
	Solarradiation   *float64  `json:"solarradiation,omitempty"`
	Solarenergy      *float64  `json:"solarenergy,omitempty"`
	Uvindex          *int32    `json:"uvindex,omitempty"`
	Severerisk       *int32    `json:"severerisk,omitempty"`
	Sunrise          *string   `json:"sunrise,omitempty"`
	SunriseEpoch     *int32    `json:"sunriseEpoch,omitempty"`
	Sunset           *string   `json:"sunset,omitempty"`
	SunsetEpoch      *int32    `json:"sunsetEpoch,omitempty"`
	Moonphase        *float64  `json:"moonphase,omitempty"`
	Conditions       *string   `json:"conditions,omitempty"`
	Description      *string   `json:"description,omitempty"`
	Icon             *string   `json:"icon,omitempty"`
	Stations         []*string `json:"stations,omitempty"`
	Source           *string   `json:"source,omitempty"`
	Hours            []*Hour   `json:"hours,omitempty"`
	Precipsum        *float64  `json:"precipsum,omitempty"`
	Precipsumnormal  *float64  `json:"precipsumnormal,omitempty"`
	Snowsum          *float64  `json:"snowsum,omitempty"`
	DatetimeInstance *string   `json:"datetimeInstance,omitempty"`
}

type Hour struct {
	Datetime         *string   `json:"datetime,omitempty"`
	DatetimeEpoch    *int32    `json:"datetimeEpoch,omitempty"`
	Temp             *float64  `json:"temp,omitempty"`
	Feelslike        *float64  `json:"feelslike,omitempty"`
	Humidity         *float64  `json:"humidity,omitempty"`
	Dew              *float64  `json:"dew,omitempty"`
	Precip           *float64  `json:"precip,omitempty"`
	Precipprob       *float64  `json:"precipprob,omitempty"`
	Snow             *float64  `json:"snow,omitempty"`
	Snowdepth        *float64  `json:"snowdepth,omitempty"`
	Preciptype       []*string `json:"preciptype,omitempty"`
	Windgust         *float64  `json:"windgust,omitempty"`
	Windspeed        *float64  `json:"windspeed,omitempty"`
	Winddir          *float64  `json:"winddir,omitempty"`
	Pressure         *float64  `json:"pressure,omitempty"`
	Visibility       *float64  `json:"visibility,omitempty"`
	Cloudcover       *float64  `json:"cloudcover,omitempty"`
	Solarradiation   *float64  `json:"solarradiation,omitempty"`
	Solarenergy      *float64  `json:"solarenergy,omitempty"`
	Uvindex          *int32    `json:"uvindex,omitempty"`
	Severerisk       *int32    `json:"severerisk,omitempty"`
	Conditions       *string   `json:"conditions,omitempty"`
	Icon             *string   `json:"icon,omitempty"`
	Stations         []*string `json:"stations,omitempty"`
	Source           *string   `json:"source,omitempty"`
	DatetimeInstance *string   `json:"datetimeInstance,omitempty"`
}

type Query struct {
}

type Station struct {
	ID           *string  `json:"id,omitempty"`
	Name         *string  `json:"name,omitempty"`
	Distance     *float64 `json:"distance,omitempty"`
	Latitude     *float64 `json:"latitude,omitempty"`
	Longitude    *float64 `json:"longitude,omitempty"`
	UseCount     *int32   `json:"useCount,omitempty"`
	Quality      *int32   `json:"quality,omitempty"`
	Contribution *int32   `json:"contribution,omitempty"`
}

type WeatherResponse struct {
	QueryCost         *int32             `json:"queryCost,omitempty"`
	Latitude          *float64           `json:"latitude,omitempty"`
	Longitude         *float64           `json:"longitude,omitempty"`
	ResolvedAddress   *string            `json:"resolvedAddress,omitempty"`
	Address           *string            `json:"address,omitempty"`
	Timezone          *string            `json:"timezone,omitempty"`
	Tzoffset          *float64           `json:"tzoffset,omitempty"`
	Description       *string            `json:"description,omitempty"`
	Days              []*Day             `json:"days,omitempty"`
	CurrentConditions *CurrentConditions `json:"currentConditions,omitempty"`
	Alerts            []*string          `json:"alerts,omitempty"`
	Stations          []*Station         `json:"stations,omitempty"`
	IsProcessed       *bool              `json:"isProcessed,omitempty"`
}
